In [1]:
import torch
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(weights='DEFAULT')
in_features = model.roi_heads.box_predictor.cls_score.in_features
model.roi_heads.box_predictor = FastRCNNPredictor(in_features, 2)
model.load_state_dict(torch.load("model1.pth", map_location=torch.device("cpu")))
model.eval()

FasterRCNN(
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
      Resize(min_size=(800,), max_size=1333, mode='bilinear')
  )
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): FrozenBatchNorm2d(64, eps=0.0)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): FrozenBatchNorm2d(64, eps=0.0)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): FrozenBatchNorm2d(64, eps=0.0)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): FrozenBatchNorm2d(256, eps=0.0)
          (relu): ReLU(

In [ ]:
import cv2
import numpy as np
cap = cv2.VideoCapture(0)

while cap.isOpened():
    _, frame = cap.read()
    orig_frame = frame.copy()
    image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).astype(np.float32)
    image /= 255.0
    image = np.transpose(image, (2, 0, 1)).astype(float)
    image = torch.tensor(image, dtype=torch.float)
    image = torch.unsqueeze(image, 0)
    with torch.no_grad():
        outputs = model(image)

    outputs = [{k: v.to('cpu') for k, v in t.items()} for t in outputs]
    if len(outputs[0]['boxes']) != 0:
        boxes = outputs[0]['boxes'].data.numpy()
        scores = outputs[0]['scores'].data.numpy()
        boxes = boxes[scores >= 0.8].astype(np.int32)
        draw_boxes = boxes.copy()
        print(draw_boxes)

        for _, box in enumerate(draw_boxes):
            cv2.rectangle(
                orig_frame,
                (int(box[0]), int(box[1])),
                (int(box[2]), int(box[3])),
                (0, 0, 255),  # Red color
                2
            )
            print("drawing")

    cv2.imshow('EyeTrack', orig_frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
    

2024-03-27 11:45:14.341 python[24356:1001452] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.


[[498  50 941 546]]
drawing
[[471  13 906 485]]
drawing
[[573  66 840 367]]
drawing
[[535  27 849 383]]
drawing
[[510  35 823 405]]
drawing
[[628  34 936 382]
 [373 343 552 557]]
drawing
drawing
[[627  38 935 388]
 [395 315 583 527]]
drawing
drawing
[[613  36 927 382]
 [357 341 515 536]]
drawing
drawing
[[608  37 907 383]
 [342 388 508 584]]
drawing
drawing
[[469  84 781 470]]
drawing
[[474  94 794 475]]
drawing
[[473  98 784 476]]
drawing
[[465  89 786 476]]
drawing
[[465  94 785 474]]
drawing
[[467  93 786 478]]
drawing
[[467  94 783 477]]
drawing
[[469  95 783 476]]
drawing
[[465  92 796 492]]
drawing
[[456  85 804 501]]
drawing
[[459  95 794 480]]
drawing
[[467 105 783 476]]
drawing
[[471  98 777 494]]
drawing
[[464 102 785 487]]
drawing
[[ 452   25  793  388]
 [1155  122 1279  296]]
drawing
drawing
[[ 478    3  892  441]
 [1173  232 1280  418]]
drawing
drawing
[[ 441   23  846  459]
 [ 932  258 1083  447]]
drawing
drawing
[[ 444   21  844  464]
 [ 948  243 1093  431]]
drawing
draw